spring:
  application:
    name: demo
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/demo_db
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    suffix: .html
server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: on_param
spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 10MB
